version: '3.7'


services:
  db:
    image: postgres:latest
    container_name: payment_db
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "payment"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "payment_db"
  
  api:
    container_name: payment_ms
    restart: on-failure
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://payment:password@db/payment_db"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-8080}:8000'
    #command: bash -c "../wait-for-it/wait-for-it.sh db:5432 -- diesel migration run && cargo run --release"